# Generated by Django 5.2.8 on 2026-06-06 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_record_collector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(max_length=20)),
                ('ghana_card', models.CharField(max_length=20)),
                ('town', models.CharField(choices=[('Nsuta', 'Nsuta'), ('Beposo', 'Beposo'), ('Kwamang', 'Kwamang'), ('Jeduako', 'Jeduako'), ('Bonkrong', 'Bonkrong'), ('Amoamang', 'Amoamang'), ('Kyebi', 'Kyebi'), ('Atonsu', 'Atonsu'), ('Birem', 'Birem'), ('Kyeiase', 'Kyeiase')], max_length=50)),
                ('area', models.CharField(max_length=200)),
                ('structure_type', models.CharField(choices=[('Container Shop', 'Container Shop'), ('Wooden Kiosk', 'Wooden Kiosk'), ('Metal Kiosk', 'Metal Kiosk'), ('Food Stall', 'Food Stall'), ('Canopy', 'Canopy'), ('Temporary Shed', 'Temporary Shed'), ('Other', 'Other')], max_length=50)),
                ('permit_status', models.CharField(choices=[('PAID', 'Paid'), ('ARREARS', 'Arrears'), ('NOT_REGISTERED', 'Not Registered')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('evidence_photo', models.ImageField(upload_to='evidence_photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
