# Generated by Django 5.2.8 on 2026-06-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_alter_user_collector_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='COLLECTOR', max_length=20),
        ),
    ]
