# Generated by Django 5.2.8 on 2026-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COLLECTOR', 'Collector')], default='COLLECTOR', max_length=20),
        ),
    ]
